"use client";

import React from "react";
import "./globals.scss";
import { Roboto } from "next/font/google";
import Header from "../components/header/header";
const roboto = Roboto({ weight: ["300"], subsets: ["latin"] });

export const metadata = {
  title: "Webbles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
